### ISSUE TITLE
No module named 'sksurgeryimage.ui'

### ISSUE THREAD

**Issue by liushuya7** [UCL/scikit-surgeryutils#41]
Hi,

Since scikit-surgeryvtk doesn't run on Linux due to changes from vtk 9.0.1, I am trying to run the same program on windows. However, I encountered this problem:
```bash
  File "vtkoverlay_app.py", line 8, in <module>
    from sksurgeryutils.common_overlay_apps import OverlayBaseApp
  File "${PYTHON_PATH}\lib\site-packages\sksurgeryutils\common_overlay_apps.py", line 12, in <module>
    from sksurgeryimage.ui.ImageCropper import ImageCropper
ModuleNotFoundError: No module named 'sksurgeryimage.ui'
```

Environment:
- Windows 10
- Python 3.8.10

**Comment by thompson318** [comment]
Thanks for spotting this. I made some changes sksurgeryvtk when trying to get things working on Ubuntu, which in included getting rid of the image cropper which I didn't think was used anywhere else. This should be fixed now, you'll need to update to scikit-surgeryutils 1.1.0.

**Comment by liushuya7** [comment]
Thanks, @thompson318 for fixing this! It works on Windows now but still doesn't work on Ubuntu yet. Since I am a Linux user, it would be so nice to have scikit-surgeryvtk working on Linux.

**Comment by thompson318** [comment]
Thanks for the feedback, I'll close this issue. Issue https://github.com/SciKit-Surgery/scikit-surgeryvtk/issues/181 remains open, hopefully we'll get to the bottom of it and get surgeryvtk working on linux again.
